{
 "title": "dashboard_Novacelik",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"display:flex; justify-content:center; align-items:center; height:100%;\">\r\n  <img src=\"/public/img/9novacelik.jpg\" style=\"max-width:250px; height:auto;\">\r\n</div>"
   }
  },
  {
   "title": "Power Factor",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  time,\r\n  \"value\"\r\nFROM \"Power Factor\"\r\nWHERE $__timeFilter(time)\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "solarGridShare",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  100.0 * solar / NULLIF(total,0) AS \"Solar %\",\r\n  100.0 * grid  / NULLIF(total,0) AS \"Grid %\"\r\nFROM \"solarGridShare\"\r\nWHERE $__timeFilter(time)\r\nORDER BY time DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Energy Cost baht/kWh",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  time,\r\n  \"value\"\r\nFROM \"Energy Consumption\"\r\nWHERE $__timeFilter(time)\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Energy Consumption/day (kWh)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 6 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  time,\r\n  \"value\"\r\nFROM \"Energy Consumption\"\r\nWHERE $__timeFilter(time)\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Power Factor",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 6 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  time,\r\n  \"value\"\r\nFROM \"Power Factor\"\r\nWHERE $__timeFilter(time)\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "table",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 12 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  DATE_BIN(INTERVAL '1 day', time) AS Date,\r\n  SUM(value) AS \"Energy Consumption (kWh)\"\r\nFROM \"Energy Consumption\"\r\nWHERE $__timeFilter(time)\r\nGROUP BY Date\r\nORDER BY Date;"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  DATE_BIN(INTERVAL '1 day', time) AS Date,\r\n  AVG(value) AS \"Power Factor\"\r\nFROM \"Power Factor\"\r\nWHERE $__timeFilter(time)\r\nGROUP BY Date\r\nORDER BY Date;"
    },
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  DATE_BIN(INTERVAL '1 day', time) AS Date,\r\n  AVG(value) AS \"CO2\"\r\nFROM \"CO2\"\r\nWHERE $__timeFilter(time)\r\nGROUP BY Date\r\nORDER BY Date;"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 16 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  time,\r\n  \"value\"\r\nFROM \"CO2\"\r\nWHERE $__timeFilter(time)\r\nORDER BY time"
    }
   ]
  }
 ]
}